name: Build Flet APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          
      - name: Install Flet
        run: pip install flet
        
      - name: Build APK
        # flet-cli가 알아서 flutter sdk를 설치하도록 하고, --yes 옵션으로 자동화합니다.
        run: python -m flet.cli build apk --module-name app --yes
        
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/apk/app-release.apk
